---

language: bash

env:
  - distro=centos7 init=/sbin/init

services:
  - docker

before_install:
  - 'docker pull uclalibrary/docker-${distro}-ansible:latest'

branches:
  only:
  - master

# Assume we've named our GitHub repo the same as our role
script:
  - role_name=${TRAVIS_BUILD_DIR##*/}
  - container_id=$(mktemp)
  - idempotence=$(mktemp)
  - 'docker run --detach --privileged --volume="${PWD}":/etc/ansible/roles/${role_name}:ro --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro uclalibrary/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/${role_name}/playbooks/test_install.yml --syntax-check'
#  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook -l localhost -v /etc/ansible/roles/${role_name}/playbooks/test_install.yml'
